const RandomNames = [
    "Ethan Anony",
    "Olivia Anony",
    "Michael Anony",
    "Sophia Anony",
    "Daniel Anony",
    "Emily Anony",
    "James Anony",
    "Ava Anony",
    "William Anony",
    "Isabella Anony",
    "Chen Anony",
    "Li Anony",
    "Wang Anony",
    "Zhang Anony",
    "Liu Anony",
    "Wei Anony",
    "Ming Anony",
    "Jun Anony",
    "Hao Anony",
    "Lin Anony",
    "Benjamin Anony",
    "Charlotte Anony",
    "Alexander Anony",
    "Amelia Anony",
    "Lucas Anony",
    "Harper Anony",
    "Henry Anony",
    "Evelyn Anony",
    "Matthew Anony",
    "Grace Anony",
  ];

export default RandomNames