"""
Django settings for bmc project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from env_config import Config

# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
