# Generated by Django 6.0.1 on 2026-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Phone_Number', models.IntegerField()),
                ('Content', models.TextField()),
                ('Image_1', models.URLField(blank=True)),
                ('Image_2', models.URLField(blank=True)),
                ('Image_3', models.URLField(blank=True)),
                ('Image_4', models.URLField(blank=True)),
                ('Image_5', models.URLField(blank=True)),
            ],
        ),
    ]
