# Generated by Django 6.0.1 on 2026-02-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Content',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Image_1',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Image_2',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Image_3',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Image_4',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='Image_5',
            field=models.URLField(blank=True, default='https://i.pinimg.com/736x/76/f3/f3/76f3f3007969fd3b6db21c744e1ef289.jpg'),
        ),
    ]
