# Generated by Django 6.0.1 on 2026-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_userdetail_content_alter_userdetail_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Content',
            field=models.TextField(),
        ),
    ]
