# Generated by Django 6.0.1 on 2026-02-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_userdetail_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Phone_Number',
            field=models.CharField(max_length=15),
        ),
    ]
